### ISSUE TITLE
Clean up JSON

### ISSUE THREAD

**Issue by AdamN2424** [kloudsoft91/mushroom_db_app#28]
JSON data needs to be organized fully by Sunday. Those of you who have data whether in a branch or not should organize it in the format described in Data Discord channel, (we should remove stipe.height though, we only need length).

I'll clean up my 6 today and push it to main. 

If you haven't researched any/just have a couple, don't bother doing any more. Just prepare what you've already researched by Sunday evening.

**Comment by kloudsoft91** [comment]
@DiscountHomebrand @joel-yap @AdamN2424 @EmilyClare4 Could everyone use the admin UI (https://kloudsoft91.github.io/mushroom_db_app_admin_gui/) and insert your metadata on the new branch (https://github.com/kloudsoft91/mushroom_db_app/tree/merge-data-branch) by this weekend please? Looks like this task fell to the wayside

**Comment by AdamN2424** [comment]
I already cleaned up most of the data before the prototype (other than fields that we haven't figured out yet like NZ Books). I'm planning on changing the lookalike field a bit but is there any reason we should do this via the GUI?

**Comment by kloudsoft91** [comment]
> I already cleaned up most of the data before the prototype (other than fields that we haven't figured out yet like NZ Books). I'm planning on changing the lookalike field a bit but is there any reason we should do this via the GUI?

To do user testing on the admin ui and to ensure that the 2 apps tie data fields together correctly (I’m looking at the json in the master branch and it does not seem to conform to the format that we agreed to on discord). For those who have entered their mushroom data already in the master branch, you can paste your data into the ui and it should allow you to edit and re-format it, it may seem like double work, but it would be nice to plug any holes in both apps sooner :)
