### ISSUE TITLE
mushroom-detail page needs functionality

### ISSUE THREAD

**Issue by EmilyClare4** [kloudsoft91/mushroom_db_app#29]
Cards now link to mushroom-detail page when 'Details' button is clicked - logic needs to be updated to get the correct details for each mushroom

**Comment by AdamN2424** [comment]
Steve would like some functionality that allows the user to click some metadata (that we have filters for) and be taken to the results page with only that filter applied.

**Comment by EmilyClare4** [comment]
> Steve would like some functionality that allows the user to click some metadata (that we have filters for) and be taken to the results page with only that filter applied.

So from the specific mushroom-detail page that's about one species, click a filter that goes back to the results page with that filter applied? I'll look in to it

**Comment by EmilyClare4** [comment]
Updated
